POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
  "fullName": "Nevada Allen",
  "username": "n.johannah@gmail.com",
  "password": "nevada",
  "verifyPassword": "nevada",
}

###

GET http://localhost:3000/dashboard
content-type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImxhdXJlbkBnbWFpbC5jb20iLCJyb2xlcyI6WzE2MF19LCJpYXQiOjE2NTk2NDY1MzgsImV4cCI6MTY1OTY0NjU2OH0._ZFsw8SrRSM-yDYcycejUatUB0rjxN6Xgd5-hkk2MQ8

###

GET http://localhost:3000/shorten/pQcWWwcqzgB
content-type: application/json


